name: websokNullSafety
description: A high level websocket library. Use it when working with websockets to avoid a few boilerplate and make your code look cleaner.
version: 2.1.1
author: João Pedro Freire
homepage: https://github.com/jpfs/
repository: https://github.com/djpfs/WbsokNullSafety
documentation: https://github.com/djpfs/WebsokNullSafety
issue_tracker: https://github.com/djpfs/WebsokNullSafety/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  web_socket_channel: ^2.1.0

dev_dependencies:
  test: ^1.9.4
